### PR TITLE
Apidocumentation

### PR DESCRIPTION
**Pull request by sampler36**
##  Questions (If any):

### CODE REVIEW

**Review by BenjaminGrabow — DISMISSED** [review]
Awesome job !

**Review by Kellswork — COMMENTED** [review]
Nice work on the documentation Antonio. Can we have the request and response in back ticks(` `). give it a code like feel

**Comment by sampler36** [comment]
> Nice work on the documentation Antonio. Can we have the request and response in back ticks(` `). give it a code like feel

Done Kells

**Review by BenjaminGrabow — APPROVED** [review]
Awesome work!

**Pull request merged**
