### PR TITLE
Ft start workout session

### PR DESCRIPTION
**Pull request by Kellswork**
##  What does this PR do
This PR adds endpoint that records when a user starts a workout. Also adds a test for the endpoint

##  Description of task to be completed
- add controller for endpoint
- add route for endpoint
- update workout-session migration file to contain userId
- write tests for endpoint

##  How should this manually be tested
clone this repository
checkout  to branch ft-start-workout-session

Make sure to add a valid token to the Authorisation header

On Postman 
`http://localhost:5000/workouts/2/start `

To Test: `run npm test`

##  What are the relevant Trello board stories
[As a user, I want to be able to start a workout session](https://trello.com/c/G1elObQt/58-as-a-user-i-want-to-be-able-to-start-a-workout-session)

### CODE REVIEW

**Comment by Kellswork** [comment]
[As a user, I want to be able to start a workout session](https://trello.com/c/G1elObQt/58-as-a-user-i-want-to-be-able-to-start-a-workout-session)

**Comment by Kellswork** [comment]
[As a user, I want to be able to start a workout session](https://trello.com/c/G1elObQt/58-as-a-user-i-want-to-be-able-to-start-a-workout-session)

**Review by Lockers — APPROVED** [review]
Tested manually, returns 400 when workout is already going
Returns 404 when no workout present

All tests pass

Great great work Kells!!
Keep it up

**Comment by Kellswork** [comment]
Thanks Matt. it's not supposed to go into an infinite loop. Yes it blocks a user from starting another workout if they haven't finished  a workout they started.

**Comment by Lockers** [comment]
> Thanks Matt. it's not supposed to go into an infinite loop. Yes it blocks a user from starting another workout if they haven't finished a workout they started.

Ahh, I mean the request doesn't end itself, just times out I think. But then each subsequent request gives workout in progress 400 error, I just assumed it was because it needed ending by the end workout call

**Review by haywhyze — APPROVED** [review]
Great Work @Kellswork

**Pull request merged**
